ifeq ($(CONFIG_ALTERNATE_MSM_HOTPLUGS),y)
obj-$(CONFIG_ALUCARD_HOTPLUG)     += alucard_hotplug.o
obj-$(CONFIG_ASMP)	          += autosmp.o
obj-$(CONFIG_KT_ARM_AUTO_HOTPLUG) += kt_auto_hotplug.o
obj-$(CONFIG_BRICKED_HOTPLUG)	  += bricked_hotplug.o
obj-$(CONFIG_INTELLI_PLUG)	  += intelli_plug.o
obj-$(CONFIG_ZEN_DECISION)	  += msm_zen_decision.o
endif
